#!/bin/bash


obj=$(node - <<EOF
var pomParser = require("pom-parser");
// The required options, including the filePath.
// Other parsing options from https://github.com/Leonidas-from-XIV/node-xml2js#options
var opts = {
  filePath: __dirname + "/pom.xml", // The path to a pom file
};
// Parse the pom based on a path
pomParser.parse(opts, function(err, pomResponse) {
  if (err) {
    console.log("ERROR: " + err);
    process.exit(1);
  }
 
  // The parsed pom pbject.
  console.log(JSON.stringify(pomResponse.pomObject));
});

EOF)

echo "${obj}" |jq .
